(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={mode:'contractor',file:null,model:null,revisionFile:null,revisionModel:null,audit:null,curve:null,hist:null,contract:[],curveChart:null,histChart:null,settings:{apiBase:localStorage.getItem('lps_api_base')||'',learning:localStorage.getItem('lps_learning')==='1',retainRaw:localStorage.getItem('lps_retain_raw')==='1'}};
const DISCIPLINE_RULES=[
 ['Tubulação',/tubula|piping|pipe\b|spool|solda|weld/i],['Elétrica',/el[eé]tric|cabo|cable|eletrocalha|painel|transformador|lumin[aá]ria/i],['Instrumentação',/instrument|transmissor|sensor|v[aá]lvula de controle|fibra/i],['Mecânica',/mec[aâ]nic|equipamento|equipment|bomba|pump|compressor|blower|motor|alinhamento/i],['Civil',/civil|concreto|concrete|funda[cç][aã]o|escava|paviment/i],['Estrutura Metálica',/estrutura met[aá]lica|steel structure|estrutura\b|structural/i],['Pintura',/pintura|painting|coating|jateamento/i],['Andaime',/andaime|scaffold/i],['Isolamento',/isolamento|insulation/i],['Refratário',/refrat|refractory/i],['Comissionamento',/comission|commission|startup|start-up|energiza|teste funcional/i]
];
const normalize=s=>(s??'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:0};
const toDate=v=>{if(!v)return null;const d=new Date(v);return isNaN(d)?null:d};
const fmtDate=v=>{const d=toDate(v);return d?d.toLocaleDateString('pt-BR'):'—'};
const iso=d=>d?new Date(d).toISOString().slice(0,10):null;
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const startOfWeek=d=>{const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x};
const startOfMonth=d=>new Date(d.getFullYear(),d.getMonth(),1);
const durationHours=s=>{if(!s)return 0;if(/^P/i.test(s)){const m=String(s).match(/P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?/i);return m?(num(m[1])*24+num(m[2])+num(m[3])/60+num(m[4])/3600):0}return num(s)};
const text=(el,tag)=>el?.getElementsByTagName(tag)?.[0]?.textContent?.trim()||'';
const directChildren=(el,tag)=>[...(el?.children||[])].filter(x=>x.localName===tag||x.tagName===tag);
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,3500)}
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function hashText(s){if(!crypto?.subtle)return Promise.resolve('');return crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)).then(b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join(''))}
function scopeTasks(model=state.model){if(!model)return[];const sec=$('#filterSector')?.value||'',area=$('#filterArea')?.value||'',disc=$('#filterDiscipline')?.value||'';return model.tasks.filter(t=>(!sec||t.sector===sec)&&(!area||t.area===area)&&(!disc||t.discipline===disc))}
function parseXmlString(xmlText,sourceName='schedule.xml'){
 const doc=new DOMParser().parseFromString(xmlText,'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML inválido.');
 const root=doc.documentElement.localName.toLowerCase();
 if(root.includes('project')&&doc.getElementsByTagName('Task').length)return parseMSPDI(doc,sourceName);
 if(doc.getElementsByTagName('Activity').length)return parseP6XML(doc,sourceName);
 throw new Error('XML reconhecido, mas o formato do cronograma não foi identificado.');
}
function parseMSPDI(doc,sourceName){
 const project=doc.documentElement;const fieldNames={};
 [...doc.getElementsByTagName('ExtendedAttribute')].forEach(x=>{const n=text(x,'FieldName'),id=text(x,'FieldID');if(n&&id)fieldNames[id]=n});
 const tasks=[...doc.getElementsByTagName('Task')].map((x,i)=>{
   const custom={};directChildren(x,'ExtendedAttribute').forEach(e=>{const id=text(e,'FieldID'),v=text(e,'Value');if(v)custom[fieldNames[id]||id]=v});
   const baselines=directChildren(x,'Baseline').map(b=>({id:text(b,'Number')||'0',start:text(b,'Start'),finish:text(b,'Finish'),workHours:durationHours(text(b,'Work')),cost:num(text(b,'Cost'))})).filter(b=>b.start||b.finish||b.workHours||b.cost);
   const predecessors=directChildren(x,'PredecessorLink').map(p=>({uid:text(p,'PredecessorUID'),type:relationType(text(p,'Type')),lagHours:num(text(p,'LinkLag'))/600}));
   const tp=directChildren(x,'TimephasedData').map(parseTimephased).filter(Boolean);
   return {uid:text(x,'UID')||String(i+1),id:text(x,'ID')||String(i+1),wbs:text(x,'WBS')||text(x,'OutlineNumber'),name:text(x,'Name')||`Atividade ${i+1}`,outlineLevel:num(text(x,'OutlineLevel')),summary:text(x,'Summary')==='1',milestone:text(x,'Milestone')==='1',start:text(x,'Start'),finish:text(x,'Finish'),actualStart:text(x,'ActualStart'),actualFinish:text(x,'ActualFinish'),durationHours:durationHours(text(x,'Duration')),workHours:durationHours(text(x,'Work')),actualWorkHours:durationHours(text(x,'ActualWork')),remainingWorkHours:durationHours(text(x,'RemainingWork')),percentComplete:num(text(x,'PercentComplete')),physicalPercent:num(text(x,'PhysicalPercentComplete')),totalFloatHours:durationHours(text(x,'TotalSlack')),critical:text(x,'Critical')==='1',constraintType:text(x,'ConstraintType'),constraintDate:text(x,'ConstraintDate'),predecessors,successors:[],baselines,timephased:tp,resourceNames:[],custom};
 }).filter(t=>t.name);
 const resources=[...doc.getElementsByTagName('Resource')].map(r=>({uid:text(r,'UID'),name:text(r,'Name'),group:text(r,'Group'),type:text(r,'Type')})).filter(r=>r.name);
 const resMap=Object.fromEntries(resources.map(r=>[r.uid,r]));
 const taskMap=Object.fromEntries(tasks.map(t=>[t.uid,t]));
 const assignments=[...doc.getElementsByTagName('Assignment')].map(a=>({uid:text(a,'UID'),taskUid:text(a,'TaskUID'),resourceUid:text(a,'ResourceUID'),workHours:durationHours(text(a,'Work')),actualWorkHours:durationHours(text(a,'ActualWork')),remainingWorkHours:durationHours(text(a,'RemainingWork')),timephased:directChildren(a,'TimephasedData').map(parseTimephased).filter(Boolean)}));
 assignments.forEach(a=>{const t=taskMap[a.taskUid],r=resMap[a.resourceUid];if(t){if(r?.name&&!t.resourceNames.includes(r.name))t.resourceNames.push(r.name);if(a.timephased.length)t.timephased.push(...a.timephased.map(v=>({...v,resource:r?.name||''})))}});
 finalizeRelations(tasks);inferHierarchy(tasks);
 return finalizeModel({format:'Microsoft Project XML',sourceName,project:{name:text(project,'Name')||sourceName,title:text(project,'Title'),start:text(project,'StartDate'),finish:text(project,'FinishDate'),statusDate:text(project,'StatusDate')||text(project,'CurrentDate')},tasks,resources,assignments,customFieldNames:[...new Set(Object.values(fieldNames))]});
}
function parseTimephased(x){const start=text(x,'Start'),finish=text(x,'Finish'),value=text(x,'Value');if(!start&&!value)return null;return{type:text(x,'Type'),start,finish,valueHours:durationHours(value)}}
function parseP6XML(doc,sourceName){
 const p=doc.getElementsByTagName('Project')[0]||doc.documentElement;const wbs={};
 [...doc.getElementsByTagName('WBS')].forEach(x=>{const id=text(x,'ObjectId');if(id)wbs[id]={id,name:text(x,'Name'),code:text(x,'Code'),parent:text(x,'ParentObjectId')}});
 const tasks=[...doc.getElementsByTagName('Activity')].map((x,i)=>({uid:text(x,'ObjectId')||text(x,'Id')||String(i+1),id:text(x,'Id')||String(i+1),wbsId:text(x,'WBSObjectId'),wbs:'',name:text(x,'Name')||`Atividade ${i+1}`,outlineLevel:0,summary:false,milestone:/milestone/i.test(text(x,'Type')),start:text(x,'StartDate')||text(x,'PlannedStartDate'),finish:text(x,'FinishDate')||text(x,'PlannedFinishDate'),actualStart:text(x,'ActualStartDate'),actualFinish:text(x,'ActualFinishDate'),durationHours:num(text(x,'PlannedDuration'))||num(text(x,'AtCompletionDuration'))||num(text(x,'RemainingDuration')),workHours:num(text(x,'PlannedLaborUnits')),actualWorkHours:num(text(x,'ActualLaborUnits')),remainingWorkHours:num(text(x,'RemainingLaborUnits')),percentComplete:num(text(x,'PercentComplete')),physicalPercent:num(text(x,'PhysicalPercentComplete')),totalFloatHours:num(text(x,'TotalFloat'))*8,critical:/critical/i.test(text(x,'Critical')),constraintType:text(x,'PrimaryConstraintType'),constraintDate:text(x,'PrimaryConstraintDate'),predecessors:[],successors:[],baselines:[],timephased:[],resourceNames:[],custom:{}}));
 const map=Object.fromEntries(tasks.map(t=>[t.uid,t]));
 [...doc.getElementsByTagName('Relationship')].forEach(r=>{const pre=text(r,'PredecessorActivityObjectId'),suc=text(r,'SuccessorActivityObjectId'),type=relationType(text(r,'Type')),lagHours=num(text(r,'Lag'));if(map[suc])map[suc].predecessors.push({uid:pre,type,lagHours});if(map[pre])map[pre].successors.push({uid:suc,type,lagHours})});
 tasks.forEach(t=>{if(t.wbsId&&wbs[t.wbsId]){const chain=[];let cur=wbs[t.wbsId],guard=0;while(cur&&guard++<20){chain.unshift(cur);cur=wbs[cur.parent]}t.wbs=chain.map(x=>x.code||x.name).join('.');t.outlineLevel=chain.length;t._wbsChain=chain.map(x=>x.name)}});
 const resources=[...doc.getElementsByTagName('Resource')].map(r=>({uid:text(r,'ObjectId'),name:text(r,'Name'),group:text(r,'ResourceType'),type:text(r,'ResourceType')})).filter(r=>r.name);
 inferHierarchy(tasks);
 return finalizeModel({format:'Primavera P6 XML',sourceName,project:{name:text(p,'Name')||sourceName,start:text(p,'PlannedStartDate')||text(p,'StartDate'),finish:text(p,'ScheduledFinishDate')||text(p,'FinishDate'),statusDate:text(p,'DataDate')},tasks,resources,assignments:[],customFieldNames:[]});
}
function parseXER(raw,sourceName){
 const lines=raw.replace(/\r/g,'').split('\n'),tables={};let table='',fields=[];
 for(const line of lines){if(!line)continue;const c=line.split('\t');if(c[0]==='%T'){table=c[1];tables[table]=tables[table]||[];fields=[]}else if(c[0]==='%F'){fields=c.slice(1)}else if(c[0]==='%R'&&table){const o={};fields.forEach((f,i)=>o[f]=c[i+1]??'');tables[table].push(o)}}
 const proj=tables.PROJECT?.[0]||{},wbsRows=tables.PROJWBS||[],wbs={};wbsRows.forEach(x=>wbs[x.wbs_id]={id:x.wbs_id,name:x.wbs_name,code:x.wbs_short_name,parent:x.parent_wbs_id});
 const tasks=(tables.TASK||[]).map((x,i)=>{const pct=num(x.phys_complete_pct||x.act_work_qty||0);return{uid:x.task_id||String(i+1),id:x.task_code||String(i+1),wbsId:x.wbs_id,wbs:'',name:x.task_name||`Atividade ${i+1}`,outlineLevel:0,summary:false,milestone:/mile/i.test(x.task_type||''),start:x.start_date||x.target_start_date||x.early_start_date,finish:x.end_date||x.target_end_date||x.early_end_date,actualStart:x.act_start_date,actualFinish:x.act_end_date,durationHours:num(x.target_drtn_hr_cnt||x.remain_drtn_hr_cnt),workHours:0,actualWorkHours:0,remainingWorkHours:0,percentComplete:pct,physicalPercent:pct,totalFloatHours:num(x.total_float_hr_cnt),critical:num(x.total_float_hr_cnt)<=0,constraintType:x.cstr_type||x.cstr_type2,constraintDate:x.cstr_date||x.cstr_date2,predecessors:[],successors:[],baselines:(x.target_start_date||x.target_end_date)?[{id:'target',name:'Planejado P6',start:x.target_start_date,finish:x.target_end_date,workHours:0}]:[],timephased:[],resourceNames:[],custom:{status:x.status_code||'',calendar:x.clndr_id||''}}});
 const map=Object.fromEntries(tasks.map(t=>[t.uid,t]));
 (tables.TASKPRED||[]).forEach(r=>{const pre=r.pred_task_id,suc=r.task_id,type=relationType(r.pred_type),lagHours=num(r.lag_hr_cnt);if(map[suc])map[suc].predecessors.push({uid:pre,type,lagHours});if(map[pre])map[pre].successors.push({uid:suc,type,lagHours})});
 tasks.forEach(t=>{if(t.wbsId&&wbs[t.wbsId]){const chain=[];let cur=wbs[t.wbsId],guard=0;while(cur&&guard++<20){chain.unshift(cur);cur=wbs[cur.parent]}t.wbs=chain.map(x=>x.code||x.name).join('.');t.outlineLevel=chain.length;t._wbsChain=chain.map(x=>x.name)}});
 const resources=(tables.RSRC||[]).map(r=>({uid:r.rsrc_id,name:r.rsrc_name,group:r.rsrc_type,type:r.rsrc_type})).filter(r=>r.name),resMap=Object.fromEntries(resources.map(r=>[r.uid,r]));
 const assignments=(tables.TASKRSRC||[]).map(a=>({taskUid:a.task_id,resourceUid:a.rsrc_id,workHours:num(a.target_qty||a.remain_qty)+num(a.act_reg_qty),actualWorkHours:num(a.act_reg_qty),remainingWorkHours:num(a.remain_qty),timephased:[]}));
 assignments.forEach(a=>{const t=map[a.taskUid],r=resMap[a.resourceUid];if(t){t.workHours+=a.workHours;t.actualWorkHours+=a.actualWorkHours;t.remainingWorkHours+=a.remainingWorkHours;if(r?.name&&!t.resourceNames.includes(r.name))t.resourceNames.push(r.name)}});
 inferHierarchy(tasks);
 return finalizeModel({format:'Primavera P6 XER',sourceName,project:{name:proj.proj_short_name||sourceName,start:proj.plan_start_date||proj.scd_end_date,finish:proj.scd_end_date,statusDate:proj.last_recalc_date||proj.data_date},tasks,resources,assignments,customFieldNames:[]});
}
function relationType(v){const s=normalize(v);if(['0','fs','finish to start','finish start','pr fs'].includes(s))return'FS';if(['1','ss','start to start','start start','pr ss'].includes(s))return'SS';if(['2','ff','finish to finish','finish finish','pr ff'].includes(s))return'FF';if(['3','sf','start to finish','start finish','pr sf'].includes(s))return'SF';return String(v||'FS').toUpperCase()}
function finalizeRelations(tasks){const map=Object.fromEntries(tasks.map(t=>[t.uid,t]));tasks.forEach(t=>t.predecessors.forEach(r=>{if(map[r.uid]&&!map[r.uid].successors.some(s=>s.uid===t.uid))map[r.uid].successors.push({uid:t.uid,type:r.type,lagHours:r.lagHours})}))}
function inferHierarchy(tasks){
 const learned=JSON.parse(localStorage.getItem('lps_class_rules')||'[]');const stack=[];
 tasks.forEach(t=>{while(stack.length&&stack[stack.length-1].level>=t.outlineLevel)stack.pop();const parent=stack.at(-1)?.task;if(t.summary)stack.push({level:t.outlineLevel,task:t});
   const customEntries=Object.entries(t.custom||{});const byKey=re=>customEntries.find(([k,v])=>re.test(normalize(k))&&v)?.[1];
   t.discipline=byKey(/disciplina|discipline/)||learned.find(r=>new RegExp(r.pattern,'i').test(t.name))?.discipline||DISCIPLINE_RULES.find(([,r])=>r.test(t.name))?.[0]||'';
   const chain=t._wbsChain||stack.map(s=>s.task.name);t.sector=byKey(/setor|sector|unidade|unit/)||chain[0]||'';t.area=byKey(/area|subarea|sub area/)||chain[1]||parent?.name||'';
   const weightEntry=customEntries.find(([k])=>/peso|weight|ponto|point/.test(normalize(k)));t.weight=weightEntry?num(weightEntry[1]):0;
 });
}
function finalizeModel(m){
 const starts=m.tasks.map(t=>toDate(t.start)).filter(Boolean),finishes=m.tasks.map(t=>toDate(t.finish)).filter(Boolean);if(!m.project.start&&starts.length)m.project.start=iso(new Date(Math.min(...starts)));if(!m.project.finish&&finishes.length)m.project.finish=iso(new Date(Math.max(...finishes)));
 const baselineSet=new Map();m.tasks.forEach(t=>t.baselines.forEach(b=>{const id=b.id??'0',cur=baselineSet.get(id)||{id,name:b.name||(`Linha de Base ${id==='0'?'':id}`.trim()),count:0};cur.count++;baselineSet.set(id,cur)}));m.baselines=[...baselineSet.values()].filter(b=>b.count>0);
 m.hasTimephased=m.tasks.some(t=>t.timephased?.some(v=>v.valueHours>0));m.customFieldNames=m.customFieldNames||[];return m;
}
async function parseScheduleFile(file){
 const ext=file.name.split('.').pop().toLowerCase();if(ext==='mpp')return parseMppViaApi(file);const raw=await file.text();if(ext==='xml')return parseXmlString(raw,file.name);if(ext==='xer')return parseXER(raw,file.name);if(ext==='json'){const m=JSON.parse(raw);if(!m.tasks)throw new Error('JSON sem modelo de cronograma.');inferHierarchy(m.tasks);return finalizeModel(m)}throw new Error('Formato não suportado.');
}
async function parseMppViaApi(file){const base=state.settings.apiBase.replace(/\/$/,'');if(!base)throw new Error('MPP nativo exige a API segura. Abra “API / Privacidade” e configure a URL do backend LPS.');const fd=new FormData();fd.append('file',file);fd.append('retain',state.settings.retainRaw?'true':'false');const r=await fetch(base+'/v1/parse/mpp',{method:'POST',body:fd,credentials:'include'});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`API MPP respondeu ${r.status}`);const m=await r.json();inferHierarchy(m.tasks||[]);return finalizeModel(m)}
function renderModel(){const m=state.model;if(!m)return;$('#workspace').hidden=false;$('#projectState').textContent=m.project.name||m.sourceName;$('#metricFormat').textContent=m.format;$('#metricTasks').textContent=m.tasks.filter(t=>!t.summary).length.toLocaleString('pt-BR');$('#metricBaselines').textContent=m.baselines.length;$('#metricResources').textContent=m.resources.length;$('#metricStatusDate').textContent=fmtDate(m.project.statusDate);$('#metricTimephased').textContent=m.hasTimephased?'Encontrada':'Fallback';$('#reportProject').textContent=m.project.name||m.sourceName;
 fillSelect('#filterSector',[...new Set(m.tasks.map(t=>t.sector).filter(Boolean))]);refreshAreaAndDiscipline();fillBaseline();renderHierarchy();renderMapping();syncLearningObservation(m);location.hash='#estrutura'}
function fillSelect(sel,vals){const el=$(sel),first=el.options[0];el.innerHTML='';el.append(first);vals.sort((a,b)=>a.localeCompare(b,'pt-BR')).forEach(v=>el.add(new Option(v,v)))}
function refreshAreaAndDiscipline(){const sec=$('#filterSector').value;const tasks=state.model.tasks.filter(t=>!sec||t.sector===sec);fillSelect('#filterArea',[...new Set(tasks.map(t=>t.area).filter(Boolean))]);const area=$('#filterArea').value;const tasks2=tasks.filter(t=>!area||t.area===area);fillSelect('#filterDiscipline',[...new Set(tasks2.map(t=>t.discipline).filter(Boolean))])}
function fillBaseline(){const el=$('#baselineSelect');el.innerHTML='<option value="current">Cronograma atual</option>';state.model.baselines.forEach(b=>el.add(new Option(`${b.name} · ${b.count} atividades`,String(b.id))))}
function renderHierarchy(){const tasks=state.model.tasks;const sectors=[...new Set(tasks.map(t=>t.sector).filter(Boolean))];let html='';if(!sectors.length)html='<div class="tree-node"><b>Projeto</b><small>Sem setor explícito; estrutura será tratada pelo WBS/níveis.</small></div>';else sectors.slice(0,12).forEach(s=>{const st=tasks.filter(t=>t.sector===s),areas=[...new Set(st.map(t=>t.area).filter(Boolean))];html+=`<div class="tree-node"><b>${esc(s)}</b><small>${st.filter(t=>!t.summary).length} atividades · ${areas.length} áreas</small></div>`;areas.slice(0,5).forEach(a=>{const at=st.filter(t=>t.area===a),ds=[...new Set(at.map(t=>t.discipline).filter(Boolean))];html+=`<div class="tree-node level-1"><b>${esc(a)}</b><small>${at.filter(t=>!t.summary).length} atividades · ${ds.join(' · ')||'disciplinas a classificar'}</small></div>`})});$('#hierarchyTree').innerHTML=html}
function renderMapping(){const m=state.model;const counts={sector:m.tasks.filter(t=>t.sector).length,area:m.tasks.filter(t=>t.area).length,disc:m.tasks.filter(t=>t.discipline).length,weight:m.tasks.filter(t=>t.weight>0).length};$('#mappingSummary').innerHTML=`Setor identificado em <b>${counts.sector}</b> registros · Área em <b>${counts.area}</b> · Disciplina em <b>${counts.disc}</b> · Peso explícito em <b>${counts.weight}</b>. O motor usa campos personalizados primeiro, depois WBS/hierarquia e por último classificação por nome.`}
function runAudit(){const tasks=scopeTasks().filter(t=>!t.summary),model=state.model,issues=[];if(!tasks.length)return toast('Nenhuma atividade no escopo selecionado.');const status=toDate(model.project.statusDate)||new Date();
 for(const t of tasks){if(!t.milestone&&!t.predecessors.length&&!t.successors.length)issues.push(issue('critical','Atividade órfã',t,'Sem predecessora e sem sucessora.','A atividade não participa efetivamente da rede lógica.'));else{if(!t.milestone&&!t.predecessors.length)issues.push(issue('warning','Sem predecessora',t,'Nenhum vínculo de entrada.','Pode representar início artificial ou lógica incompleta.'));if(!t.milestone&&!t.successors.length)issues.push(issue('warning','Sem sucessora',t,'Nenhum vínculo de saída.','O atraso pode não ser propagado para o término.'))}
   if(t.durationHours>160)issues.push(issue('warning','Duração longa',t,`${(t.durationHours/8).toFixed(1)} dias equivalentes.`, 'Atividades extensas reduzem a capacidade de controle.'));
   if(t.totalFloatHours<0)issues.push(issue('critical','Folga negativa',t,`${(t.totalFloatHours/8).toFixed(1)} dias.`, 'Indica prazo incompatível com restrições/datas da rede.'));
   if(t.totalFloatHours>320)issues.push(issue('warning','Folga elevada',t,`${(t.totalFloatHours/8).toFixed(1)} dias.`, 'Pode indicar lógica aberta, calendário ou vínculo insuficiente.'));
   if(t.constraintType&&!/^(0|as soon as possible|as late as possible|)$/i.test(t.constraintType))issues.push(issue(/must/i.test(t.constraintType)?'critical':'warning','Restrição de data',t,`${t.constraintType}${t.constraintDate?' · '+fmtDate(t.constraintDate):''}.`,'Restrições podem mascarar o comportamento natural da rede.'));
   t.predecessors.forEach(r=>{if(r.type!=='FS')issues.push(issue('info','Relação não FS',t,`${r.type}${r.lagHours?` · lag ${r.lagHours.toFixed(1)}h`:''}.`,'Requer validação da intenção lógica.'));if(Math.abs(r.lagHours)>40)issues.push(issue('warning','Lag elevado',t,`${r.lagHours.toFixed(1)}h na relação ${r.type}.`,'Lags extensos reduzem transparência; prefira atividades quando aplicável.'))});
   const finish=toDate(t.finish);if(finish&&finish<status&&t.percentComplete<100)issues.push(issue('critical','Atividade vencida e incompleta',t,`Término ${fmtDate(t.finish)} · avanço ${t.percentComplete.toFixed(1)}%.`,'O cronograma não reflete conclusão compatível com a Data Status.'));
   if(t.milestone&&(!t.predecessors.length||!t.successors.length))issues.push(issue('warning','Marco com lógica fraca',t,`${t.predecessors.length} predecessoras · ${t.successors.length} sucessoras.`,'Marco pode não representar corretamente o caminho de entrega.'));
 }
 const baseline=$('#baselineSelect').value;if(baseline!=='current'){const covered=tasks.filter(t=>t.baselines.some(b=>String(b.id)===baseline)).length/tasks.length;if(covered<.9)issues.unshift({severity:covered<.7?'critical':'warning',rule:'Cobertura da baseline',task:null,evidence:`${(covered*100).toFixed(1)}% das atividades possuem dados na baseline selecionada.`,impact:'Curva prevista e comparação contratual podem ficar incompletas.'})}
 const weights={critical:7,warning:2.2,info:.6};const penalty=Math.min(75,issues.reduce((a,i)=>a+weights[i.severity],0)/Math.max(1,tasks.length/100));let score=Math.max(0,Math.round(100-penalty));if(tasks.length<10)score=Math.min(score,80);
 const criticals=tasks.filter(t=>t.critical||t.totalFloatHours<=0),negative=tasks.filter(t=>t.totalFloatHours<0),orphans=tasks.filter(t=>!t.predecessors.length&&!t.successors.length&&!t.milestone);const next=findNextCritical(tasks,status);
 state.audit={score,issues,criticals,negative,orphans,next,ranAt:new Date().toISOString()};renderAudit();maybeAiOpinion();}
function issue(severity,rule,task,evidence,impact){return{severity,rule,task,evidence,impact}}
function findNextCritical(tasks,status){const candidates=tasks.filter(t=>t.percentComplete<100).map(t=>{const float=t.totalFloatHours||0,remaining=t.remainingWorkHours||t.workHours*(1-t.percentComplete/100)||t.durationHours;let risk=(float<0?70:float<=40?50:float<=80?30:10)+Math.min(20,(remaining/80)*10)+Math.min(10,t.successors.length);const st=toDate(t.start);if(st&&st<status&&t.percentComplete===0)risk+=15;return{t,risk}}).sort((a,b)=>b.risk-a.risk);return candidates[0]||null}
function renderAudit(){const a=state.audit;$('#healthScore').textContent=a.score;$('#healthLabel').textContent=a.score>=85?'Cronograma tecnicamente consistente':a.score>=70?'Aprovável com ressalvas':a.score>=50?'Revisão técnica recomendada':'Não recomendado para aprovação';$('#healthText').textContent=`Foram identificados ${a.issues.length} achados no escopo analisado.`;$('#criticalCount').textContent=a.criticals.length;$('#negativeFloatCount').textContent=a.negative.length;$('#orphanCount').textContent=a.orphans.length;$('#scoreRing').style.background=`conic-gradient(#1e5ac9 ${a.score*3.6}deg,#e2e8f0 0)`;
 const n=a.next;if(n)$('#nextCritical').innerHTML=`<b>${esc(n.t.id)} · ${esc(n.t.name)}</b><br>Risco calculado: <b>${Math.min(100,Math.round(n.risk))}/100</b> · folga ${(n.t.totalFloatHours/8).toFixed(1)} d · avanço ${n.t.percentComplete.toFixed(1)}% · ${n.t.successors.length} sucessoras.`;else $('#nextCritical').textContent='Nenhuma atividade remanescente identificada.';
 $('#autoOpinion').textContent=deterministicOpinion(a);
 $('#issuesBody').innerHTML=a.issues.length?a.issues.slice(0,500).map(i=>`<tr><td><span class="sev ${i.severity}">${i.severity==='critical'?'Crítico':i.severity==='warning'?'Alerta':'Recomendação'}</span></td><td><b>${esc(i.rule)}</b></td><td>${i.task?`${esc(i.task.id)} · ${esc(i.task.name)}`:'Projeto / escopo'}</td><td>${esc(i.evidence)}</td><td>${esc(i.impact)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Nenhum desvio detectado pelas regras executadas.</td></tr>'}
function deterministicOpinion(a){if(a.score>=85)return'Os critérios automáticos indicam boa robustez geral. Recomenda-se validar os achados remanescentes e a aderência aos marcos contratuais antes da aprovação formal.';if(a.score>=70)return'O cronograma apresenta estrutura utilizável, porém possui ressalvas que devem ser tratadas antes da aprovação definitiva, principalmente nos itens classificados como críticos.';return'O cronograma apresenta fragilidades suficientes para justificar revisão técnica antes da aprovação. As evidências listadas devem ser respondidas e corrigidas pela parte responsável.'}
async function maybeAiOpinion(){if(!state.settings.apiBase||!state.audit)return;try{const payload={mode:state.mode,project:{start:state.model.project.start,finish:state.model.project.finish,statusDate:state.model.project.statusDate},metrics:{score:state.audit.score,issues:state.audit.issues.length,critical:state.audit.issues.filter(i=>i.severity==='critical').length,negativeFloat:state.audit.negative.length,orphans:state.audit.orphans.length},topIssues:state.audit.issues.slice(0,20).map(i=>({severity:i.severity,rule:i.rule,evidence:i.evidence,impact:i.impact}))};const r=await fetch(state.settings.apiBase.replace(/\/$/,'')+'/v1/ai/report',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){const j=await r.json();if(j.opinion)$('#autoOpinion').textContent=j.opinion}}catch(e){console.warn('AI opinion unavailable',e)}}
function taskWeight(t){if(t.weight>0)return t.weight;if(t.workHours>0)return t.workHours;return 1}
function baselineDates(t,id){if(id==='current')return{start:t.start,finish:t.finish};const b=t.baselines.find(x=>String(x.id)===String(id));return{start:b?.start||t.start,finish:b?.finish||t.finish}}
function distribute(t,start,finish,value,tp){const out=[];const tps=(tp||[]).filter(x=>x.start&&x.valueHours>0);if(tps.length){const total=tps.reduce((a,x)=>a+x.valueHours,0)||1;tps.forEach(x=>out.push({date:toDate(x.start),value:value*(x.valueHours/total)}));return{values:out,fallback:false}}
 const s=toDate(start),f=toDate(finish);if(!s||!f||f<s)return{values:[],fallback:true};const days=Math.max(1,Math.round((f-s)/86400000)+1),per=value/days;for(let i=0;i<days;i++)out.push({date:addDays(s,i),value:per});return{values:out,fallback:true}}
function bucketKey(d,period='week'){if(period==='day')return iso(d);if(period==='month')return iso(startOfMonth(d));return iso(startOfWeek(d))}
function generateCurves(){const tasks=scopeTasks().filter(t=>!t.summary),base=$('#baselineSelect').value;if(!tasks.length)return toast('Nenhuma atividade no escopo.');const plan=new Map(),real=new Map();let fallback=0,totalWeight=0;const status=toDate(state.model.project.statusDate)||new Date();
 tasks.forEach(t=>{const w=taskWeight(t);totalWeight+=w;const bd=baselineDates(t,base);const p=distribute(t,bd.start,bd.finish,w,t.timephased);if(p.fallback)fallback++;p.values.forEach(x=>plan.set(bucketKey(x.date),(plan.get(bucketKey(x.date))||0)+x.value));const earned=w*Math.max(0,Math.min(100,t.physicalPercent||t.percentComplete))/100;if(earned>0){const end=toDate(t.actualFinish)||((toDate(t.finish)&&toDate(t.finish)<status)?toDate(t.finish):status);const a=distribute(t,t.actualStart||t.start,end,earned,t.timephased.filter(x=>/actual/i.test(x.type||'')));a.values.forEach(x=>real.set(bucketKey(x.date),(real.get(bucketKey(x.date))||0)+x.value))}});
 const keys=[...new Set([...plan.keys(),...real.keys()])].sort(),planned=[],actual=[];let cp=0,ca=0;keys.forEach(k=>{cp+=plan.get(k)||0;ca+=real.get(k)||0;planned.push(totalWeight?cp/totalWeight*100:0);actual.push(totalWeight?ca/totalWeight*100:0)});state.curve={keys,planned,actual,totalWeight,fallback,fallbackPct:tasks.length?fallback/tasks.length:0};renderCurve();generateHistogram();}
function renderCurve(){const c=state.curve;if(state.curveChart)state.curveChart.destroy();state.curveChart=new Chart($('#curveChart'),{type:'line',data:{labels:c.keys.map(fmtDate),datasets:[{label:'Previsto',data:c.planned,borderColor:'#1e3a8a',backgroundColor:'#1e3a8a',tension:.25,pointRadius:1.5},{label:'Real/Atual',data:c.actual,borderColor:'#1e5ac9',backgroundColor:'#1e5ac9',borderDash:[5,3],tension:.25,pointRadius:1.5}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{min:0,max:100,ticks:{callback:v=>v+'%'}}},plugins:{legend:{labels:{boxWidth:12,font:{size:10}}}}}});$('#curveBasis').textContent=c.fallback?`Base mista · ${Math.round(c.fallbackPct*100)}% das atividades sem distribuição timephased`:'Base: distribuição temporal do cronograma';$('#curveCards').innerHTML=`<div class="curve-card"><span>Peso total analisado</span><b>${c.totalWeight.toLocaleString('pt-BR',{maximumFractionDigits:1})}</b></div><div class="curve-card"><span>Previsto final</span><b>${(c.planned.at(-1)||0).toFixed(1)}%</b></div><div class="curve-card"><span>Real acumulado estimado</span><b>${(c.actual.at(-1)||0).toFixed(1)}%</b></div>`}
function generateHistogram(){const period=$('#histPeriod').value,tasks=scopeTasks().filter(t=>!t.summary),plan=new Map(),actual=new Map();let fallback=0;tasks.forEach(t=>{const work=t.workHours||0;if(!work)return;const p=distribute(t,t.start,t.finish,work,t.timephased.filter(x=>x.valueHours>0));if(p.fallback)fallback++;p.values.forEach(x=>{const k=bucketKey(x.date,period);plan.set(k,(plan.get(k)||0)+x.value)});const aw=t.actualWorkHours||0;if(aw>0){const a=distribute(t,t.actualStart||t.start,t.actualFinish||state.model.project.statusDate||t.finish,aw,t.timephased.filter(x=>/actual/i.test(x.type||'')));a.values.forEach(x=>{const k=bucketKey(x.date,period);actual.set(k,(actual.get(k)||0)+x.value)})}});const keys=[...new Set([...plan.keys(),...actual.keys()])].sort();state.hist={keys,planned:keys.map(k=>plan.get(k)||0),actual:keys.map(k=>actual.get(k)||0),fallback};renderHistogram()}
function renderHistogram(){const h=state.hist;if(state.histChart)state.histChart.destroy();state.histChart=new Chart($('#histChart'),{type:'bar',data:{labels:h.keys.map(fmtDate),datasets:[{label:'HH Previsto',data:h.planned,backgroundColor:'#1e3a8a'},{label:'HH Real',data:h.actual,backgroundColor:'#60a5fa'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{boxWidth:12,font:{size:10}}}},scales:{x:{stacked:false},y:{beginAtZero:true}}}});$('#histBasis').textContent=h.fallback?`HH distribuído com fallback em ${h.fallback} atividades`:'HH obtido da distribuição temporal'}
function exportWorkbook(){if(!state.curve)return toast('Gere as curvas antes de exportar.');if(!window.XLSX)return toast('Biblioteca de Excel ainda carregando.');const wb=XLSX.utils.book_new();const curve=[['Data','Previsto %','Real/Atual %'],...state.curve.keys.map((k,i)=>[k,state.curve.planned[i],state.curve.actual[i]])];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(curve),'Curva S');if(state.hist){const hh=[['Data','HH Previsto','HH Real'],...state.hist.keys.map((k,i)=>[k,state.hist.planned[i],state.hist.actual[i]])];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(hh),'Histograma HH')}const issues=[['Severidade','Regra','ID','Atividade','Evidência','Impacto'],...(state.audit?.issues||[]).map(i=>[i.severity,i.rule,i.task?.id||'',i.task?.name||'',i.evidence,i.impact])];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(issues),'Auditoria');XLSX.writeFile(wb,'LPS_Schedule_Intelligence.xlsx')}
function addContractRow(data={name:'',rule:'finish_by',date:''}){state.contract.push(data);renderContractInputs()}
function renderContractInputs(){$('#contractInputBody').innerHTML=state.contract.map((r,i)=>`<tr><td><input data-cidx="${i}" data-field="name" value="${esc(r.name)}" placeholder="Ex.: Mechanical Completion"></td><td><select data-cidx="${i}" data-field="rule"><option value="finish_by" ${r.rule==='finish_by'?'selected':''}>Terminar até</option><option value="start_on" ${r.rule==='start_on'?'selected':''}>Iniciar em</option><option value="start_after" ${r.rule==='start_after'?'selected':''}>Não iniciar antes</option><option value="finish_on" ${r.rule==='finish_on'?'selected':''}>Terminar em</option></select></td><td><input type="date" data-cidx="${i}" data-field="date" value="${esc(r.date)}"></td><td><button class="icon-btn" data-remove-contract="${i}">×</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">Nenhum requisito cadastrado.</td></tr>';$$('[data-cidx]').forEach(el=>el.onchange=()=>state.contract[num(el.dataset.cidx)][el.dataset.field]=el.value);$$('[data-remove-contract]').forEach(b=>b.onclick=()=>{state.contract.splice(num(b.dataset.removeContract),1);renderContractInputs()})}
function similarity(a,b){const A=new Set(normalize(a).split(' ').filter(x=>x.length>2)),B=new Set(normalize(b).split(' ').filter(x=>x.length>2));if(!A.size||!B.size)return 0;const inter=[...A].filter(x=>B.has(x)).length;return inter/Math.max(A.size,B.size)}
function checkContract(){const tasks=scopeTasks().filter(t=>!t.summary),results=[];state.contract.filter(r=>r.name&&r.date).forEach(r=>{const match=tasks.map(t=>({t,s:similarity(r.name,t.name)})).sort((a,b)=>b.s-a.s)[0];if(!match||match.s<.25){results.push({...r,status:'att',message:'Marco não localizado com confiança no cronograma.',match:null});return}const req=toDate(r.date),start=toDate(match.t.start),finish=toDate(match.t.finish);let ok=false,delta=0;if(r.rule==='finish_by'){ok=finish&&finish<=req;delta=finish?Math.round((finish-req)/86400000):0}else if(r.rule==='finish_on'){delta=finish?Math.round((finish-req)/86400000):0;ok=delta===0}else if(r.rule==='start_after'){ok=start&&start>=req;delta=start?Math.round((start-req)/86400000):0}else{delta=start?Math.round((start-req)/86400000):0;ok=delta===0}results.push({...r,status:ok?'ok':'late',message:`Correspondência: ${match.t.id} · ${match.t.name} · ${delta>0?'+':''}${delta} dias`,match:match.t})});state.contractResults=results;renderContractResults()}
function renderContractResults(){const r=state.contractResults||[],ok=r.filter(x=>x.status==='ok').length,late=r.filter(x=>x.status==='late').length,att=r.filter(x=>x.status==='att').length;$('#contractSummary').innerHTML=`<b>${r.length} requisitos avaliados</b><br>${ok} atendidos · ${late} não conformes · ${att} exigem associação manual.`;$('#contractResults').innerHTML=r.map(x=>`<div class="contract-result"><div><b>${esc(x.name)}</b><small>${esc(x.message)}</small></div><span class="tag ${x.status}">${x.status==='ok'?'ATENDIDO':x.status==='late'?'NÃO CONFORME':'VALIDAR'}</span></div>`).join('')}
async function compareRevision(){if(!state.revisionFile)return;try{toast('Lendo revisão anterior…');state.revisionModel=await parseScheduleFile(state.revisionFile);const a=state.revisionModel.tasks.filter(t=>!t.summary),b=state.model.tasks.filter(t=>!t.summary),key=t=>t.uid||normalize((t.wbs||'')+' '+t.name),am=new Map(a.map(t=>[key(t),t])),bm=new Map(b.map(t=>[key(t),t]));let added=0,removed=0,dates=0,logic=0,weights=0;for(const [k,t] of bm){if(!am.has(k)){added++;continue}const o=am.get(k);if(iso(toDate(o.start))!==iso(toDate(t.start))||iso(toDate(o.finish))!==iso(toDate(t.finish)))dates++;if(JSON.stringify(o.predecessors.map(x=>[x.uid,x.type,x.lagHours]).sort())!==JSON.stringify(t.predecessors.map(x=>[x.uid,x.type,x.lagHours]).sort()))logic++;if(Math.abs(taskWeight(o)-taskWeight(t))>.0001)weights++}for(const k of am.keys())if(!bm.has(k))removed++;state.revisionCompare={added,removed,dates,logic,weights};$('#revisionSummary').innerHTML=[['Adicionadas',added],['Removidas',removed],['Datas alteradas',dates],['Lógica alterada',logic],['Pesos/HH alterados',weights]].map(([n,v])=>`<div class="revision-stat"><span>${n}</span><b>${v}</b></div>`).join('');toast('Comparação concluída.')}catch(e){toast(e.message)}}
function buildReport(){const a=state.audit,c=state.contractResults||[],m=state.model;if(!m)return;$('#reportGrade').textContent=a?.score??'—';let html=`<section class="report-section"><h4>1. Escopo da avaliação</h4><p>Arquivo analisado: <b>${esc(m.sourceName)}</b>. Formato: ${esc(m.format)}. Foram consideradas ${scopeTasks().filter(t=>!t.summary).length} atividades no escopo selecionado. A análise automática é apoio técnico e não substitui a decisão formal do responsável pelo contrato.</p></section>`;if(a){html+=`<section class="report-section"><h4>2. Resultado da auditoria</h4><p><b>Índice de Qualidade do Cronograma: ${a.score}/100.</b> ${esc(deterministicOpinion(a))}</p><ul><li>${a.issues.filter(i=>i.severity==='critical').length} achados críticos.</li><li>${a.issues.filter(i=>i.severity==='warning').length} alertas.</li><li>${a.negative.length} atividades com folga negativa.</li><li>${a.orphans.length} atividades órfãs.</li></ul></section>`}if(c.length){html+=`<section class="report-section"><h4>3. Conformidade contratual</h4><p>Foram verificados ${c.length} requisitos: <b>${c.filter(x=>x.status==='ok').length}</b> atendidos, <b>${c.filter(x=>x.status==='late').length}</b> não conformes e <b>${c.filter(x=>x.status==='att').length}</b> pendentes de validação.</p></section>`}if(state.revisionCompare){const r=state.revisionCompare;html+=`<section class="report-section"><h4>4. Controle de revisão</h4><p>A comparação identificou ${r.added} atividades adicionadas, ${r.removed} removidas, ${r.dates} mudanças de datas, ${r.logic} mudanças de lógica e ${r.weights} alterações de peso/HH.</p></section>`}if(a?.next){html+=`<section class="report-section"><h4>5. Risco prospectivo</h4><p>Próximo ponto crítico provável: <b>${esc(a.next.t.id)} · ${esc(a.next.t.name)}</b>, com indicador de risco ${Math.min(100,Math.round(a.next.risk))}/100.</p></section>`}$('#reportBody').innerHTML=html;location.hash='#relatorio'}
function exportPdf(){buildReport();if(!window.html2pdf)return window.print();html2pdf().set({margin:8,filename:'LPS_Relatorio_Avaliacao_Cronograma.pdf',image:{type:'jpeg',quality:.96},html2canvas:{scale:2},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from($('#reportPreview')).save()}
function exportIssues(){if(!state.audit)return toast('Execute a auditoria primeiro.');const rows=[['Severidade','Regra','ID','Atividade','Evidência','Impacto'],...state.audit.issues.map(i=>[i.severity,i.rule,i.task?.id||'',i.task?.name||'',i.evidence,i.impact])];download('LPS_Achados_Auditoria.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),'text/csv;charset=utf-8')}
async function syncLearningObservation(model){if(!state.settings.learning||!state.settings.apiBase)return;try{const names=[...new Set(model.customFieldNames||[])];const hashes=await Promise.all(names.map(hashText));const payload={format:model.format,taskCount:model.tasks.length,resourceCount:model.resources.length,baselineCount:model.baselines.length,hasTimephased:model.hasTimephased,customFieldHashes:hashes.filter(Boolean),disciplineCoverage:model.tasks.length?model.tasks.filter(t=>t.discipline).length/model.tasks.length:0};fetch(state.settings.apiBase.replace(/\/$/,'')+'/v1/learning/observe',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).catch(()=>{})}catch{}}
function setup(){
 const input=$('#scheduleFile'),drop=$('#dropzone');input.onchange=e=>selectFile(e.target.files[0]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>selectFile(e.dataTransfer.files[0]));$('#btnClearFile').onclick=e=>{e.preventDefault();state.file=null;input.value='';$('#selectedFile').hidden=true;$('#btnAnalyze').disabled=true};$('#btnAnalyze').onclick=async()=>{try{$('#btnAnalyze').disabled=true;$('#btnAnalyze').textContent='Analisando…';state.model=await parseScheduleFile(state.file);renderModel();toast('Cronograma carregado e mapeado.')}catch(e){console.error(e);toast(e.message)}finally{$('#btnAnalyze').disabled=!state.file;$('#btnAnalyze').textContent='Analisar cronograma'}};
 $$('.mode-switch button').forEach(b=>b.onclick=()=>{$$('.mode-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode});
 $('#filterSector').onchange=()=>{refreshAreaAndDiscipline();if(state.audit)runAudit()};$('#filterArea').onchange=()=>{const sec=$('#filterSector').value,area=$('#filterArea').value;const tasks=state.model.tasks.filter(t=>(!sec||t.sector===sec)&&(!area||t.area===area));fillSelect('#filterDiscipline',[...new Set(tasks.map(t=>t.discipline).filter(Boolean))])};
 $('#btnValidateMapping').onclick=()=>toast('Mapeamento validado para esta sessão. Correções manuais de classificação entram na próxima interface de edição.');$('#btnRunAudit').onclick=runAudit;$('#btnExportIssues').onclick=exportIssues;$('#btnGenerateCurves').onclick=generateCurves;$('#histPeriod').onchange=()=>state.model&&generateHistogram();$('#btnExportWorkbook').onclick=exportWorkbook;$('#btnAddMilestone').onclick=()=>addContractRow();$('#btnCheckContract').onclick=checkContract;
 $('#revisionFile').onchange=e=>{state.revisionFile=e.target.files[0];$('#btnCompareRevision').disabled=!state.revisionFile};$('#btnCompareRevision').onclick=compareRevision;$('#btnBuildReport').onclick=buildReport;$('#btnPdf').onclick=exportPdf;
 $('#btnSettings').onclick=()=>{const d=$('#settingsDialog');$('#apiBase').value=state.settings.apiBase;$('#learningOptIn').checked=state.settings.learning;$('#allowRawRetention').checked=state.settings.retainRaw;d.showModal()};$('#btnSaveSettings').onclick=e=>{e.preventDefault();state.settings.apiBase=$('#apiBase').value.trim().replace(/\/$/,'');state.settings.learning=$('#learningOptIn').checked;state.settings.retainRaw=$('#allowRawRetention').checked;localStorage.setItem('lps_api_base',state.settings.apiBase);localStorage.setItem('lps_learning',state.settings.learning?'1':'0');localStorage.setItem('lps_retain_raw',state.settings.retainRaw?'1':'0');$('#settingsDialog').close();toast('Configurações salvas neste navegador.')};
 addContractRow();$$('.sidebar nav a').forEach(a=>a.addEventListener('click',()=>{$$('.sidebar nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
}
function selectFile(f){if(!f)return;state.file=f;$('#selectedName').textContent=f.name;$('#selectedSize').textContent=(f.size/1024/1024).toFixed(1)+' MB';$('#selectedFile').hidden=false;$('#btnAnalyze').disabled=false}
window.addEventListener('DOMContentLoaded',setup);
})();